import 'package:flutter/material.dart';
import 'package:online_grocery_system/categories_page/product_class.dart';

List<Product> chocolatesproducts = [
  Product(
      id: 0701,
      title: "5 Star",
      price: 10,
      size: 12,
      description: "Cadbury 5 star chocolate bar 19.5g",
      image: "App Images/Grocery Categories/7. Chocolates/image0701.jpg",
      color: Colors.teal),
  Product(
      id: 0702,
      title: "Kitkat",
      price: 10,
      size: 12,
      description: "Nestle KitKat Mini 2 Finger Wafer Bar, 12.8 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0702.jpg",
      color: Colors.teal),
  Product(
      id: 0703,
      title: "Silk Bubbly",
      price: 80,
      size: 12,
      description: "Cadbury Dairy Milk Silk Bubbly Chocolate Bar",
      image: "App Images/Grocery Categories/7. Chocolates/image0703.jpg",
      color: Colors.teal),
  Product(
      id: 0704,
      title: "Cadbury Gems",
      price: 5,
      size: 12,
      description: "Cadbury Gems Chocolate, 10.68 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0704.jpg",
      color: Colors.teal),

  Product(
      id: 0705,
      title: "Snickers",
      price: 20,
      size: 12,
      description: "Snickers Bars  22 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0705.jpg",
      color: Colors.teal),
  Product(
      id: 0706,
      title: "Galaxy Chocolate",
      price: 40,
      size: 12,
      description: "Galaxy Smooth Milk Chocolate Bar, 30 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0706.jpg",
      color: Colors.teal),
  Product(
      id: 0707,
      title: "Hershey's Chocolate",
      price: 55,
      size: 12,
      description: "Hershey's Milk Chocolate, 40 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0707.jpg",
      color: Colors.teal),
  Product(
      id: 0708,
      title: "Mars",
      price: 40,
      size: 12,
      description: "Mars Chocolate Bar",
      image: "App Images/Grocery Categories/7. Chocolates/image0708.jpg",
      color: Colors.teal),
  Product(
      id: 0709,
      title: "Silk Roast Almond",
      price: 80,
      size: 12,
      description: "Cadbury Dairy Milk Silk - Roast Almond 58g",
      image: "App Images/Grocery Categories/7. Chocolates/image0709.jpg",
      color: Colors.teal),
  Product(
      id: 0710,
      title: "Ferrero Rocher",
      price: 549,
      size: 12,
      description: "Ferrero Rocher 16 Pieces",
      image: "App Images/Grocery Categories/7. Chocolates/image0710.jpg",
      color: Colors.teal),
  Product(
      id: 0711,
      title: "Bournville",
      price: 45,
      size: 12,
      description: "Cadbury Bournville Rich Cocoa Dark Chocolate Bars, 31 g",
      image: "App Images/Grocery Categories/7. Chocolates/image0711.jpg",
      color: Colors.teal),
  Product(
      id: 0712,
      title: "Silk Fruit & Nut",
      price: 76,
      size: 12,
      description: "Cadbury Dairy Milk Silk Fruit and Nut Chocolate Bars  (55 g)",
      image: "App Images/Grocery Categories/7. Chocolates/image0712.jpg",
      color: Colors.teal),
];