import 'package:flutter/material.dart';
import 'package:online_grocery_system/categories_page/product_class.dart';

List<Product> frozenfoodproducts = [
  Product(
      id: 0601,
      title: "Bru Gold Coffee",
      price: 144,
      size: 12,
      description: "Bru Gold Instant Coffee, 50g",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0601.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0602,
      title: "Coca-Cola",
      price: 81,
      size: 12,
      description: "Coca-Cola Soft Drink, 1.75L PET Bottle",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0602.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0603,
      title: "Frooti Drink",
      price: 20,
      size: 12,
      description: "Frooti Drink - Fresh 'N' Juicy Mango 300ml Bottle",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0603.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0604,
      title: "Lipton Green Tea",
      price: 139,
      size: 12,
      description: "Lipton Green Tea Tulsi Natural, 20 Tea Bags",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0604.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0605,
      title: "Maaza Drink",
      price: 56,
      size: 12,
      description: "Maaza Mango Drink, 1.2L PET Bottle",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0605.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0606,
      title: "Mirinda Soft Drink",
      price: 25,
      size: 12,
      description: "Mirinda Soft Drink with Added Orange Flavour, 250ml",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0606.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0607,
      title: "Nescafe Coffee",
      price: 150,
      size: 12,
      description: "Nescafe Classic Instant Coffee, 100g",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0607.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0608,
      title: "Red Label",
      price: 305,
      size: 12,
      description: "Red Label Natural Care Tea, 500g",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0608.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0609,
      title: "Tropicana Juice",
      price: 50,
      size: 12,
      description: "Tropicana Juice - Slice Mango, 1.2L",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0609.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0610,
      title: "Sprite",
      price: 25,
      size: 12,
      description: "Sprite can, 250ml",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0610.jpg",
      color: Colors.deepPurpleAccent),
  Product(
      id: 0611,
      title: "Thumbs Up",
      price: 52,
      size: 12,
      description: "Thumbs Up Soft Drink, 1.25L",
      image: "App Images/Grocery Categories/6. Frozen food-beverages/image0611.png",
      color: Colors.deepPurpleAccent),
];