import 'package:flutter/material.dart';
import 'package:online_grocery_system/categories_page/product_class.dart';

List<Product> fruitsproducts = [
  Product(
      id: 21,
      title: "Apple",
      price: 100,
      size: 12,
      description: "Rs. 100 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image01.jpg",
      color: Colors.amberAccent),
  Product(
      id: 22,
      title: "Banana",
      price: 60,
      size: 12,
      description: "Rs. 60 per dozen",
      image: "App Images/Grocery Categories/2. Fruits/image02.jpg",
      color: Colors.amberAccent),
  Product(
      id: 23,
      title: "Grapes",
      price: 90,
      size: 12,
      description: "Rs. 90 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image03.jpg",
      color: Colors.amberAccent),
  Product(
      id: 24,
      title: "Guava",
      price: 90,
      size: 12,
      description: "Rs. 90 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image04.jpg",
      color: Colors.amberAccent),
  Product(
      id: 25,
      title: "Kiwi",
      price: 140,
      size: 12,
      description: "Rs. 140 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image05.jpg",
      color: Colors.amberAccent),
  Product(
      id: 26,
      title: "Mango",
      price: 60,
      size: 12,
      description: "Rs. 60 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image06.jpg",
      color: Colors.amberAccent),
  Product(
      id: 27,
      title: "Orange",
      price: 50,
      size: 12,
      description: "Rs. 50 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image07.jpg",
      color: Colors.amberAccent),
  Product(
      id: 28,
      title: "Papaya",
      price: 60,
      size: 12,
      description: "Rs. 60 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image08.jpg",
      color: Colors.amberAccent),
  Product(
      id: 29,
      title: "Pear",
      price: 45,
      size: 12,
      description: "Rs. 45 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image09.jpg",
      color: Colors.amberAccent),
  Product(
      id: 210,
      title: "Pineapple",
      price: 35,
      size: 12,
      description: "Rs. 35 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image10.jpg",
      color: Colors.amberAccent),
  Product(
      id: 211,
      title: "Pomegranate",
      price: 100,
      size: 12,
      description: "Rs. 100 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image11.jpg",
      color: Colors.amberAccent),
  Product(
      id: 212,
      title: "Watermelon",
      price: 30,
      size: 12,
      description: "Rs. 30 per kg",
      image: "App Images/Grocery Categories/2. Fruits/image12.jpg",
      color: Colors.amberAccent),
];