import 'package:flutter/material.dart';
import 'package:online_grocery_system/categories_page/product_class.dart';

List<Product> personalcareproducts = [
  Product(
      id: 0901,
      title: "Bajaj Almond Drops",
      price: 320,
      size: 12,
      description: "Bajaj Almond Drops Premium hair oil 500 ml ",
      image: "App Images/Grocery Categories/9. Personal Care/image0901.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0902,
      title: "Biotique skin lotion",
      price: 250,
      size: 12,
      description: "Biotique (Bio Morning Nectar Flawless skin lotion), 190ml",
      image: "App Images/Grocery Categories/9. Personal Care/image0902.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0903,
      title: "Deo stick",
      price: 60,
      size: 12,
      description: "Cinthol Energy Deo stick, 40g",
      image: "App Images/Grocery Categories/9. Personal Care/image0903.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0904,
      title: "Clean & Clear Face Wash",
      price: 306,
      size: 12,
      description: "Clean & Clear Oil Free Foaming Face Wash, 300ml",
      image: "App Images/Grocery Categories/9. Personal Care/image0904.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0905,
      title: "Dettol Soap",
      price: 216,
      size: 12,
      description: "Dettol Original Germ Protection Bathing Soap (3 x 125 g)",
      image: "App Images/Grocery Categories/9. Personal Care/image0905.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0906,
      title: "Dove Shampoo & Conditioner",
      price: 419,
      size: 12,
      description: "Dove Daily Shine Shampoo (340 ML) With Daily Shine Conditioner (180 ML)  (2 Items in the set)",
      image: "App Images/Grocery Categories/9. Personal Care/image0906.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0907,
      title: "Mouth Wash",
      price: 280,
      size: 12,
      description: "Listerine Mouth Wash - Cool Mint  (750 ml)",
      image: "App Images/Grocery Categories/9. Personal Care/image0907.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0908,
      title: "Coconut Hair Oil",
      price: 180,
      size: 12,
      description: "Parachute Coconut Hair Oil For All Hair Types, 200 ml",
      image: "App Images/Grocery Categories/9. Personal Care/image0908.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0909,
      title: "Dabur Toothpaste",
      price: 225,
      size: 12,
      description: "Dabur Red Toothpaste, 300 g",
      image: "App Images/Grocery Categories/9. Personal Care/image0909.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0910,
      title: "Santoor Soap",
      price: 172,
      size: 12,
      description: "Santoor Sandal & Turmeric Soap  (4 x 150 g)",
      image: "App Images/Grocery Categories/9. Personal Care/image0910.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0911,
      title: "Gillette Shave Foam",
      price: 199,
      size: 12,
      description: "Gillette Sensitive Skin Shave Foam  (418 g)",
      image: "App Images/Grocery Categories/9. Personal Care/image0911.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0912,
      title: "Vaseline Petroleum Jelly",
      price: 318,
      size: 12,
      description: "Vaseline Pure Petroleum Jelly Original, 250 ml",
      image: "App Images/Grocery Categories/9. Personal Care/image0912.jpg",
      color: Colors.indigoAccent),
  Product(
      id: 0913,
      title: "Vaseline Cocoa Lotion",
      price: 345,
      size: 12,
      description: "Vaseline Intensive Care Cocoa Glow Body Lotion, (400 ml)",
      image: "App Images/Grocery Categories/9. Personal Care/image0913.jpg",
      color: Colors.indigoAccent),
];