import 'package:flutter/material.dart';
import 'package:online_grocery_system/categories_page/product_class.dart';

List<Product> vegetablesproducts = [
  Product(
      id: 11,
      title: "Onions",
      price: 50,
      size: 12,
      description: "Rs. 50 per kg",
      image: "App Images/Grocery Categories/1. Vegetables/image01.jpg",
      color: Colors.blueAccent),
  Product(
      id: 12,
      title: "Potato",
      price: 50,
      size: 12,
      description: "Rs. 50 per kg",
      image: "App Images/Grocery Categories/1. Vegetables/image02.jpg",
      color: Colors.blueAccent),
  Product(
      id: 13,
      title: "Tomato",
      price: 20,
      size: 12,
      description: "Rs. 20 per kg",
      image: "App Images/Grocery Categories/1. Vegetables/image03.jpg",
      color: Colors.blueAccent),
  Product(
      id: 14,
      title: "Green Chilly",
      price: 20,
      size: 12,
      description: "Rs. 20 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image04.jpg",
      color: Colors.blueAccent),
  Product(
      id: 15,
      title: "Lady Finger",
      price: 20,
      size: 12,
      description: "Rs. 20 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image05.jpg",
      color: Colors.blueAccent),
  Product(
      id: 16,
      title: "Capsicum",
      price: 20,
      size: 12,
      description: "Rs. 20 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image06.jpg",
      color: Colors.blueAccent),
  Product(
      id: 17,
      title: "Cauliflower",
      price: 15,
      size: 12,
      description: "Rs. 15 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image07.jpg",
      color: Colors.blueAccent),
  Product(
      id: 18,
      title: "Cucumber",
      price: 20,
      size: 12,
      description: "Rs. 20 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image08.jpg",
      color: Colors.blueAccent),
  Product(
      id: 19,
      title: "Cabbage",
      price: 15,
      size: 12,
      description: "Rs. 15 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image09.jpg",
      color: Colors.blueAccent),
  Product(
      id: 110,
      title: "Carrots",
      price: 10,
      size: 12,
      description: "Rs. 10 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image10.jpg",
      color: Colors.blueAccent),
  Product(
      id: 111,
      title: "Beetroot",
      price: 15,
      size: 12,
      description: "Rs. 15 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image11.jpg",
      color: Colors.blueAccent),
  Product(
      id: 112,
      title: "Broccoli",
      price: 30,
      size: 12,
      description: "Rs. 30 per 250g",
      image: "App Images/Grocery Categories/1. Vegetables/image12.jpg",
      color: Colors.blueAccent),
];